apiVersion: v2
name: transporter
description: A Kubernetes pod migration tool using CRDs and gRPC

# This is the chart version. This documentation is at https://helm.sh/docs/topics/charts/
# It should be a SemVer 2.0.0 compliant version
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "1.0"

keywords:
  - migration
  - pod
  - kubernetes

maintainers:
  - name: transporter-maintainer
    email: maintainer@example.com