// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: pkg/agent/api/migration.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MigrationClient is the client API for Migration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MigrationClient interface {
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
	StartMigration(ctx context.Context, in *StartMigrationRequest, opts ...grpc.CallOption) (*StartMigrationResponse, error)
	ApplyLayer(ctx context.Context, in *ApplyLayerRequest, opts ...grpc.CallOption) (*ApplyLayerResponse, error)
	TransferMemory(ctx context.Context, opts ...grpc.CallOption) (Migration_TransferMemoryClient, error)
	TransferFilesystem(ctx context.Context, opts ...grpc.CallOption) (Migration_TransferFilesystemClient, error)
}

type migrationClient struct {
	cc grpc.ClientConnInterface
}

func NewMigrationClient(cc grpc.ClientConnInterface) MigrationClient {
	return &migrationClient{cc}
}

func (c *migrationClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, "/api.Migration/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) StartMigration(ctx context.Context, in *StartMigrationRequest, opts ...grpc.CallOption) (*StartMigrationResponse, error) {
	out := new(StartMigrationResponse)
	err := c.cc.Invoke(ctx, "/api.Migration/StartMigration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) ApplyLayer(ctx context.Context, in *ApplyLayerRequest, opts ...grpc.CallOption) (*ApplyLayerResponse, error) {
	out := new(ApplyLayerResponse)
	err := c.cc.Invoke(ctx, "/api.Migration/ApplyLayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) TransferMemory(ctx context.Context, opts ...grpc.CallOption) (Migration_TransferMemoryClient, error) {
	stream, err := c.cc.NewStream(ctx, &Migration_ServiceDesc.Streams[0], "/api.Migration/TransferMemory", opts...)
	if err != nil {
		return nil, err
	}
	x := &migrationTransferMemoryClient{stream}
	return x, nil
}

type Migration_TransferMemoryClient interface {
	Send(*MemoryChunk) error
	CloseAndRecv() (*TransferResponse, error)
	grpc.ClientStream
}

type migrationTransferMemoryClient struct {
	grpc.ClientStream
}

func (x *migrationTransferMemoryClient) Send(m *MemoryChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *migrationTransferMemoryClient) CloseAndRecv() (*TransferResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TransferResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *migrationClient) TransferFilesystem(ctx context.Context, opts ...grpc.CallOption) (Migration_TransferFilesystemClient, error) {
	stream, err := c.cc.NewStream(ctx, &Migration_ServiceDesc.Streams[1], "/api.Migration/TransferFilesystem", opts...)
	if err != nil {
		return nil, err
	}
	x := &migrationTransferFilesystemClient{stream}
	return x, nil
}

type Migration_TransferFilesystemClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*TransferResponse, error)
	grpc.ClientStream
}

type migrationTransferFilesystemClient struct {
	grpc.ClientStream
}

func (x *migrationTransferFilesystemClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *migrationTransferFilesystemClient) CloseAndRecv() (*TransferResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TransferResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MigrationServer is the server API for Migration service.
// All implementations must embed UnimplementedMigrationServer
// for forward compatibility
type MigrationServer interface {
	Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error)
	StartMigration(context.Context, *StartMigrationRequest) (*StartMigrationResponse, error)
	ApplyLayer(context.Context, *ApplyLayerRequest) (*ApplyLayerResponse, error)
	TransferMemory(Migration_TransferMemoryServer) error
	TransferFilesystem(Migration_TransferFilesystemServer) error
	mustEmbedUnimplementedMigrationServer()
}

// UnimplementedMigrationServer must be embedded to have forward compatible implementations.
type UnimplementedMigrationServer struct {
}

func (UnimplementedMigrationServer) Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedMigrationServer) StartMigration(context.Context, *StartMigrationRequest) (*StartMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMigration not implemented")
}
func (UnimplementedMigrationServer) ApplyLayer(context.Context, *ApplyLayerRequest) (*ApplyLayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyLayer not implemented")
}
func (UnimplementedMigrationServer) TransferMemory(Migration_TransferMemoryServer) error {
	return status.Errorf(codes.Unimplemented, "method TransferMemory not implemented")
}
func (UnimplementedMigrationServer) TransferFilesystem(Migration_TransferFilesystemServer) error {
	return status.Errorf(codes.Unimplemented, "method TransferFilesystem not implemented")
}
func (UnimplementedMigrationServer) mustEmbedUnimplementedMigrationServer() {}

// UnsafeMigrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigrationServer will
// result in compilation errors.
type UnsafeMigrationServer interface {
	mustEmbedUnimplementedMigrationServer()
}

func RegisterMigrationServer(s grpc.ServiceRegistrar, srv MigrationServer) {
	s.RegisterService(&Migration_ServiceDesc, srv)
}

func _Migration_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Migration/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_StartMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).StartMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Migration/StartMigration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).StartMigration(ctx, req.(*StartMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_ApplyLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyLayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).ApplyLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Migration/ApplyLayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).ApplyLayer(ctx, req.(*ApplyLayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_TransferMemory_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MigrationServer).TransferMemory(&migrationTransferMemoryServer{stream})
}

type Migration_TransferMemoryServer interface {
	SendAndClose(*TransferResponse) error
	Recv() (*MemoryChunk, error)
	grpc.ServerStream
}

type migrationTransferMemoryServer struct {
	grpc.ServerStream
}

func (x *migrationTransferMemoryServer) SendAndClose(m *TransferResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *migrationTransferMemoryServer) Recv() (*MemoryChunk, error) {
	m := new(MemoryChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Migration_TransferFilesystem_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MigrationServer).TransferFilesystem(&migrationTransferFilesystemServer{stream})
}

type Migration_TransferFilesystemServer interface {
	SendAndClose(*TransferResponse) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type migrationTransferFilesystemServer struct {
	grpc.ServerStream
}

func (x *migrationTransferFilesystemServer) SendAndClose(m *TransferResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *migrationTransferFilesystemServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Migration_ServiceDesc is the grpc.ServiceDesc for Migration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Migration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Migration",
	HandlerType: (*MigrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _Migration_Prepare_Handler,
		},
		{
			MethodName: "StartMigration",
			Handler:    _Migration_StartMigration_Handler,
		},
		{
			MethodName: "ApplyLayer",
			Handler:    _Migration_ApplyLayer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferMemory",
			Handler:       _Migration_TransferMemory_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TransferFilesystem",
			Handler:       _Migration_TransferFilesystem_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/agent/api/migration.proto",
}
