// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/agent/api/migration.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_pkg_agent_api_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_migration_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PrepareRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

type PrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_pkg_agent_api_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_migration_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrepareResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	TargetAddress string                 `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	ContainerId   string                 `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"` // Exact container to migrate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMigrationRequest) Reset() {
	*x = StartMigrationRequest{}
	mi := &file_pkg_agent_api_migration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMigrationRequest) ProtoMessage() {}

func (x *StartMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_migration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMigrationRequest.ProtoReflect.Descriptor instead.
func (*StartMigrationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_migration_proto_rawDescGZIP(), []int{2}
}

func (x *StartMigrationRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *StartMigrationRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *StartMigrationRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *StartMigrationRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StartMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMigrationResponse) Reset() {
	*x = StartMigrationResponse{}
	mi := &file_pkg_agent_api_migration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMigrationResponse) ProtoMessage() {}

func (x *StartMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_migration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMigrationResponse.ProtoReflect.Descriptor instead.
func (*StartMigrationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_migration_proto_rawDescGZIP(), []int{3}
}

func (x *StartMigrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartMigrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApplyLayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	ContainerId   string                 `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"` // For tracking newly created ghost pods
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyLayerRequest) Reset() {
	*x = ApplyLayerRequest{}
	mi := &file_pkg_agent_api_migration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyLayerRequest) ProtoMessage() {}

func (x *ApplyLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_migration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyLayerRequest.ProtoReflect.Descriptor instead.
func (*ApplyLayerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_migration_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyLayerRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ApplyLayerRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *ApplyLayerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type ApplyLayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyLayerResponse) Reset() {
	*x = ApplyLayerResponse{}
	mi := &file_pkg_agent_api_migration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyLayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyLayerResponse) ProtoMessage() {}

func (x *ApplyLayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_migration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyLayerResponse.ProtoReflect.Descriptor instead.
func (*ApplyLayerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_migration_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyLayerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyLayerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SignalHandoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalHandoverRequest) Reset() {
	*x = SignalHandoverRequest{}
	mi := &file_pkg_agent_api_migration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalHandoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalHandoverRequest) ProtoMessage() {}

func (x *SignalHandoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_migration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalHandoverRequest.ProtoReflect.Descriptor instead.
func (*SignalHandoverRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_migration_proto_rawDescGZIP(), []int{6}
}

func (x *SignalHandoverRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *SignalHandoverRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

type SignalHandoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalHandoverResponse) Reset() {
	*x = SignalHandoverResponse{}
	mi := &file_pkg_agent_api_migration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalHandoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalHandoverResponse) ProtoMessage() {}

func (x *SignalHandoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_migration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalHandoverResponse.ProtoReflect.Descriptor instead.
func (*SignalHandoverResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_migration_proto_rawDescGZIP(), []int{7}
}

func (x *SignalHandoverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignalHandoverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MemoryChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryChunk) Reset() {
	*x = MemoryChunk{}
	mi := &file_pkg_agent_api_migration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryChunk) ProtoMessage() {}

func (x *MemoryChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_migration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryChunk.ProtoReflect.Descriptor instead.
func (*MemoryChunk) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_migration_proto_rawDescGZIP(), []int{8}
}

func (x *MemoryChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MemoryChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_pkg_agent_api_migration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_migration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_migration_proto_rawDescGZIP(), []int{9}
}

func (x *FileChunk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_pkg_agent_api_migration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_migration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_migration_proto_rawDescGZIP(), []int{10}
}

func (x *TransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_agent_api_migration_proto protoreflect.FileDescriptor

const file_pkg_agent_api_migration_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/agent/api/migration.proto\x12\x03api\"P\n" +
	"\x0ePrepareRequest\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\"E\n" +
	"\x0fPrepareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa1\x01\n" +
	"\x15StartMigrationRequest\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12%\n" +
	"\x0etarget_address\x18\x03 \x01(\tR\rtargetAddress\x12!\n" +
	"\fcontainer_id\x18\x04 \x01(\tR\vcontainerId\"L\n" +
	"\x16StartMigrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"v\n" +
	"\x11ApplyLayerRequest\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\"H\n" +
	"\x12ApplyLayerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\x15SignalHandoverRequest\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\"L\n" +
	"\x16SignalHandoverResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\vMemoryChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"3\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"F\n" +
	"\x10TransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9e\x03\n" +
	"\tMigration\x126\n" +
	"\aPrepare\x12\x13.api.PrepareRequest\x1a\x14.api.PrepareResponse\"\x00\x12K\n" +
	"\x0eStartMigration\x12\x1a.api.StartMigrationRequest\x1a\x1b.api.StartMigrationResponse\"\x00\x12?\n" +
	"\n" +
	"ApplyLayer\x12\x16.api.ApplyLayerRequest\x1a\x17.api.ApplyLayerResponse\"\x00\x12K\n" +
	"\x0eSignalHandover\x12\x1a.api.SignalHandoverRequest\x1a\x1b.api.SignalHandoverResponse\"\x00\x12=\n" +
	"\x0eTransferMemory\x12\x10.api.MemoryChunk\x1a\x15.api.TransferResponse\"\x00(\x01\x12?\n" +
	"\x12TransferFilesystem\x12\x0e.api.FileChunk\x1a\x15.api.TransferResponse\"\x00(\x01B\x1bZ\x19transporter/pkg/agent/apib\x06proto3"

var (
	file_pkg_agent_api_migration_proto_rawDescOnce sync.Once
	file_pkg_agent_api_migration_proto_rawDescData []byte
)

func file_pkg_agent_api_migration_proto_rawDescGZIP() []byte {
	file_pkg_agent_api_migration_proto_rawDescOnce.Do(func() {
		file_pkg_agent_api_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_api_migration_proto_rawDesc), len(file_pkg_agent_api_migration_proto_rawDesc)))
	})
	return file_pkg_agent_api_migration_proto_rawDescData
}

var file_pkg_agent_api_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_agent_api_migration_proto_goTypes = []any{
	(*PrepareRequest)(nil),         // 0: api.PrepareRequest
	(*PrepareResponse)(nil),        // 1: api.PrepareResponse
	(*StartMigrationRequest)(nil),  // 2: api.StartMigrationRequest
	(*StartMigrationResponse)(nil), // 3: api.StartMigrationResponse
	(*ApplyLayerRequest)(nil),      // 4: api.ApplyLayerRequest
	(*ApplyLayerResponse)(nil),     // 5: api.ApplyLayerResponse
	(*SignalHandoverRequest)(nil),  // 6: api.SignalHandoverRequest
	(*SignalHandoverResponse)(nil), // 7: api.SignalHandoverResponse
	(*MemoryChunk)(nil),            // 8: api.MemoryChunk
	(*FileChunk)(nil),              // 9: api.FileChunk
	(*TransferResponse)(nil),       // 10: api.TransferResponse
}
var file_pkg_agent_api_migration_proto_depIdxs = []int32{
	0,  // 0: api.Migration.Prepare:input_type -> api.PrepareRequest
	2,  // 1: api.Migration.StartMigration:input_type -> api.StartMigrationRequest
	4,  // 2: api.Migration.ApplyLayer:input_type -> api.ApplyLayerRequest
	6,  // 3: api.Migration.SignalHandover:input_type -> api.SignalHandoverRequest
	8,  // 4: api.Migration.TransferMemory:input_type -> api.MemoryChunk
	9,  // 5: api.Migration.TransferFilesystem:input_type -> api.FileChunk
	1,  // 6: api.Migration.Prepare:output_type -> api.PrepareResponse
	3,  // 7: api.Migration.StartMigration:output_type -> api.StartMigrationResponse
	5,  // 8: api.Migration.ApplyLayer:output_type -> api.ApplyLayerResponse
	7,  // 9: api.Migration.SignalHandover:output_type -> api.SignalHandoverResponse
	10, // 10: api.Migration.TransferMemory:output_type -> api.TransferResponse
	10, // 11: api.Migration.TransferFilesystem:output_type -> api.TransferResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_agent_api_migration_proto_init() }
func file_pkg_agent_api_migration_proto_init() {
	if File_pkg_agent_api_migration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_api_migration_proto_rawDesc), len(file_pkg_agent_api_migration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_api_migration_proto_goTypes,
		DependencyIndexes: file_pkg_agent_api_migration_proto_depIdxs,
		MessageInfos:      file_pkg_agent_api_migration_proto_msgTypes,
	}.Build()
	File_pkg_agent_api_migration_proto = out.File
	file_pkg_agent_api_migration_proto_goTypes = nil
	file_pkg_agent_api_migration_proto_depIdxs = nil
}
