// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pkg/agent/api/migration.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Migration_Prepare_FullMethodName            = "/api.Migration/Prepare"
	Migration_StartMigration_FullMethodName     = "/api.Migration/StartMigration"
	Migration_ApplyLayer_FullMethodName         = "/api.Migration/ApplyLayer"
	Migration_SignalHandover_FullMethodName     = "/api.Migration/SignalHandover"
	Migration_TransferMemory_FullMethodName     = "/api.Migration/TransferMemory"
	Migration_TransferFilesystem_FullMethodName = "/api.Migration/TransferFilesystem"
)

// MigrationClient is the client API for Migration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MigrationClient interface {
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
	StartMigration(ctx context.Context, in *StartMigrationRequest, opts ...grpc.CallOption) (*StartMigrationResponse, error)
	ApplyLayer(ctx context.Context, in *ApplyLayerRequest, opts ...grpc.CallOption) (*ApplyLayerResponse, error)
	SignalHandover(ctx context.Context, in *SignalHandoverRequest, opts ...grpc.CallOption) (*SignalHandoverResponse, error)
	TransferMemory(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MemoryChunk, TransferResponse], error)
	TransferFilesystem(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, TransferResponse], error)
}

type migrationClient struct {
	cc grpc.ClientConnInterface
}

func NewMigrationClient(cc grpc.ClientConnInterface) MigrationClient {
	return &migrationClient{cc}
}

func (c *migrationClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, Migration_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) StartMigration(ctx context.Context, in *StartMigrationRequest, opts ...grpc.CallOption) (*StartMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartMigrationResponse)
	err := c.cc.Invoke(ctx, Migration_StartMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) ApplyLayer(ctx context.Context, in *ApplyLayerRequest, opts ...grpc.CallOption) (*ApplyLayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyLayerResponse)
	err := c.cc.Invoke(ctx, Migration_ApplyLayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) SignalHandover(ctx context.Context, in *SignalHandoverRequest, opts ...grpc.CallOption) (*SignalHandoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalHandoverResponse)
	err := c.cc.Invoke(ctx, Migration_SignalHandover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationClient) TransferMemory(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MemoryChunk, TransferResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Migration_ServiceDesc.Streams[0], Migration_TransferMemory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MemoryChunk, TransferResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Migration_TransferMemoryClient = grpc.ClientStreamingClient[MemoryChunk, TransferResponse]

func (c *migrationClient) TransferFilesystem(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, TransferResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Migration_ServiceDesc.Streams[1], Migration_TransferFilesystem_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, TransferResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Migration_TransferFilesystemClient = grpc.ClientStreamingClient[FileChunk, TransferResponse]

// MigrationServer is the server API for Migration service.
// All implementations must embed UnimplementedMigrationServer
// for forward compatibility.
type MigrationServer interface {
	Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error)
	StartMigration(context.Context, *StartMigrationRequest) (*StartMigrationResponse, error)
	ApplyLayer(context.Context, *ApplyLayerRequest) (*ApplyLayerResponse, error)
	SignalHandover(context.Context, *SignalHandoverRequest) (*SignalHandoverResponse, error)
	TransferMemory(grpc.ClientStreamingServer[MemoryChunk, TransferResponse]) error
	TransferFilesystem(grpc.ClientStreamingServer[FileChunk, TransferResponse]) error
	mustEmbedUnimplementedMigrationServer()
}

// UnimplementedMigrationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMigrationServer struct{}

func (UnimplementedMigrationServer) Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedMigrationServer) StartMigration(context.Context, *StartMigrationRequest) (*StartMigrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartMigration not implemented")
}
func (UnimplementedMigrationServer) ApplyLayer(context.Context, *ApplyLayerRequest) (*ApplyLayerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyLayer not implemented")
}
func (UnimplementedMigrationServer) SignalHandover(context.Context, *SignalHandoverRequest) (*SignalHandoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalHandover not implemented")
}
func (UnimplementedMigrationServer) TransferMemory(grpc.ClientStreamingServer[MemoryChunk, TransferResponse]) error {
	return status.Error(codes.Unimplemented, "method TransferMemory not implemented")
}
func (UnimplementedMigrationServer) TransferFilesystem(grpc.ClientStreamingServer[FileChunk, TransferResponse]) error {
	return status.Error(codes.Unimplemented, "method TransferFilesystem not implemented")
}
func (UnimplementedMigrationServer) mustEmbedUnimplementedMigrationServer() {}
func (UnimplementedMigrationServer) testEmbeddedByValue()                   {}

// UnsafeMigrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigrationServer will
// result in compilation errors.
type UnsafeMigrationServer interface {
	mustEmbedUnimplementedMigrationServer()
}

func RegisterMigrationServer(s grpc.ServiceRegistrar, srv MigrationServer) {
	// If the following call panics, it indicates UnimplementedMigrationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Migration_ServiceDesc, srv)
}

func _Migration_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migration_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_StartMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).StartMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migration_StartMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).StartMigration(ctx, req.(*StartMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_ApplyLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyLayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).ApplyLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migration_ApplyLayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).ApplyLayer(ctx, req.(*ApplyLayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_SignalHandover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalHandoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServer).SignalHandover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migration_SignalHandover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServer).SignalHandover(ctx, req.(*SignalHandoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migration_TransferMemory_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MigrationServer).TransferMemory(&grpc.GenericServerStream[MemoryChunk, TransferResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Migration_TransferMemoryServer = grpc.ClientStreamingServer[MemoryChunk, TransferResponse]

func _Migration_TransferFilesystem_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MigrationServer).TransferFilesystem(&grpc.GenericServerStream[FileChunk, TransferResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Migration_TransferFilesystemServer = grpc.ClientStreamingServer[FileChunk, TransferResponse]

// Migration_ServiceDesc is the grpc.ServiceDesc for Migration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Migration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Migration",
	HandlerType: (*MigrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _Migration_Prepare_Handler,
		},
		{
			MethodName: "StartMigration",
			Handler:    _Migration_StartMigration_Handler,
		},
		{
			MethodName: "ApplyLayer",
			Handler:    _Migration_ApplyLayer_Handler,
		},
		{
			MethodName: "SignalHandover",
			Handler:    _Migration_SignalHandover_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferMemory",
			Handler:       _Migration_TransferMemory_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TransferFilesystem",
			Handler:       _Migration_TransferFilesystem_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/agent/api/migration.proto",
}
