{{- if .Values.migrationAgent.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "transporter.fullname" . }}-migration-agent
  labels:
    {{- include "transporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "transporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "transporter.selectorLabels" . | nindent 8 }}
    spec:
      hostPID: true
      hostNetwork: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "transporter.serviceAccountName" . }}
      containers:
        - name: migration-agent
          securityContext:
            privileged: true
          image: "{{ .Values.migrationAgent.image.repository }}:{{ .Values.migrationAgent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.migrationAgent.image.pullPolicy }}
          volumeMounts:
            - name: host-root
              mountPath: /host
              readOnly: false
            - name: containerd-sock
              mountPath: /run/containerd/containerd.sock
          ports:
          {{- with .Values.migrationAgent.ports }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- with .Values.migrationAgent.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: host-root
          hostPath:
            path: /
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
